# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-11 10:12
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('all_posts', '0002_auto_20170210_2204'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='draft',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='posts',
            name='publish',
            field=models.DateField(default=datetime.datetime(2017, 2, 11, 10, 12, 28, 543506, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
